apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
spec:
  selector:
    matchLabels:
      app: vets
  replicas: 2
  template:
    metadata:
      labels:
        app: vets
    spec:
      containers:
        - name: vets
          image: jamessukk/spring-petclinic-vets-service:1.0.0.RELEASE
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: vets
  labels:
    svc: vets
spec:
  selector:
    app: vets
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
